# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex
instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  warmup_requests: true

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"
